### ISSUE TITLE
More Button Please?

### ISSUE THREAD

**Issue by ardissaps** [MSDNicrosoft/Command-GUI-Buttons#2]
Would you like to add more button? Thank you very much. (1.18.2)

**Comment by MSDNicrosoft** [comment]
Sorry, I just learned **Java**.
I will try to seek help from my friends as much as possible.

**Comment by LeChocolatChaud** [comment]
You can probably implement a page system so that you wouldn't need to rewrite the existing code. @MSDNicrosoft

**Comment by MSDNicrosoft** [comment]
The featured version will be released soon.
