### ISSUE TITLE
Commands not going through

### ISSUE THREAD

**Issue by mathewschroder** [MSDNicrosoft/Command-GUI-Buttons#3]
So I use this mod to save commands for carpet mod, commands that essentially controlling the player but for what ever reason it sends it as a message instead of the command its self. It used to work on 1,18 but now after updating to 1.19 I broke.

**Comment by MSDNicrosoft** [comment]
I have fixed this bug, please try [the latest release](https://github.com/MSDNicrosoft/Command-GUI-Buttons/releases/latest) below.
