### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by verixyt3** [MSDNicrosoft/Command-GUI-Buttons#47]
Hello, I'm asking you to make a version for _1.20.2 fabric or quilt on Modrinth_, **thank you very much!**

**Comment by MSDNicrosoft** [comment]
I'm sorry, but the dependency `LibGui` for this mod has not been updated to support 1.20.2 yet. Therefore, I am unable to update the project to support 1.20.2. Please be patient and wait.

**Comment by Q2Lummox** [comment]
Hello, the LibGui dependency has already been updated to version 1.20.2

Would it be possible to update the mod to be compatible with version 1.20.2?

Thank you very much for the effort.

**Comment by MSDNicrosoft** [comment]
I will update this mod soon.
