### ISSUE TITLE
please upload dependency on modrinth

### ISSUE THREAD

**Issue by ardissaps** [MSDNicrosoft/Command-GUI-Buttons#53]

**Comment by PalmarHealer** [comment]
I don't know if that is possible what you want because the mod it needs is not on modrinth so you really can't take any advantage from it. You have to download it from here: https://github.com/CottonMC/LibGui/releases

**Comment by MSDNicrosoft** [comment]
Sorry, `LibGui` is not my project, and I can't do this without authorization. Please submit issue in its repository https://github.com/CottonMC/LibGui/issues
