### ISSUE TITLE
Crash When Pressing Command

### ISSUE THREAD

**Issue by ardissaps** [MSDNicrosoft/Command-GUI-Buttons#6]
https://mclo.gs/jAzVUnA

**Comment by MSDNicrosoft** [comment]
Hmm, can you tell me what command you executed?

**Comment by ardissaps** [comment]
/fabrication:client ui, it is command to open config for that mod.

**Comment by MSDNicrosoft** [comment]
I see,I will fix it and update this mod to support `1.19.2`.

**Comment by MSDNicrosoft** [comment]
I have fixed this bug and update this mod to support `1.19.2`.
Please try the latest version `1.0.7`([Modrinth](https://modrinth.com/mod/command-gui-buttons/version/1.0.7)).

**Comment by ardissaps** [comment]
> I have fixed this bug and update this mod to support `1.19.2`. Please try the latest version `1.0.7`([Modrinth](https://modrinth.com/mod/command-gui-buttons/version/1.0.7)).

thanks, it worked!

**Comment by MSDNicrosoft** [comment]
Thank you for reporting this bug.
