### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by xxxkingxl** [MSDNicrosoft/Command-GUI-Buttons#69]
can you please update to 1.21?

**Comment by xxxkingxl** [comment]
I have asked LibGUI to update to mc 1.21

**Comment by xxxkingxl** [comment]
![image](https://github.com/MSDNicrosoft/Command-GUI-Buttons/assets/101728597/44b81322-5ae0-4c27-b5d6-a490f501968c)
LibGUI has already updated

**Comment by MSDNicrosoft** [comment]
Updated
