### ISSUE TITLE
add multicommand, please

### ISSUE THREAD

**Issue by erxson** [MSDNicrosoft/Command-GUI-Buttons#7]
&& between two or more commands or just button to add one more command

**Comment by MSDNicrosoft** [comment]
I see.
But I have other things to do, please be patient.

**Comment by MSDNicrosoft** [comment]
I have implemented this feature. Please try the latest version `1.1.0` [Modrinth](https://modrinth.com/mod/command-gui-buttons/version/1.1.0).


In addition, you have to pay attention to the following:
>I uses ` && ` as the delimiter for multiple commands.  
>**Notice**: There is **a space around** `&&`  
>e.g. `/help && /gamemode creative && hello`

**Comment by erxson** [comment]
thanks!
